<h1>Nuestros productos</h1>

<?php while($product = $products->fetch_object()) :?>
    <div class="product">
        <a href="<?=base_url?>product/view&id=<?=$product->id?>">
            <?php if( !is_null($product->imagen) ) :?>
                <img src="<?=base_url?>/uploads/images/<?=$product->imagen;?>" />
            <?php else :?>
                <img src="/assets/img/camiseta.png" />
            <?php endif;?>
            <h2><?=$product->nombre ?></h2>
        </a>
        <p>$<?=$product->precio ?></p>
        <a href="<?=base_url?>cart/add&id=<?=$product->id?>" class="button" >Comprar</a>
    </div>
<?php endwhile; ?>