<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="<?=base_url?>assets/css/styles.css">
    <title>Tienda de Ropa</title>
</head>
<body>
<!-- CABECERA -->
    <header id="header">
        <div id="logo">
            <img src="<?=base_url?>assets/img/camiseta.png" alt="Camiseta Logo">
            <a href="<?=base_url?>">
                <h1>Tienda de Ropa</h1>
            </a>
        </div>
    </header>
<!-- MENU -->
    <?php $categories = Utils::showCategories();?>
    <nav id="menu">
        <ul>
            <li>
                <a href="<?=base_url?>">Inicio</a>
            </li>
            <?php while($cat = $categories->fetch_object() ) :?>
                <li>
                    <a href="<?=base_url?>category/products&id=<?=$cat->id?>"><?=$cat->nombre?></a>
                </li>
            <?php endwhile;?>
        </ul>
    </nav>

    <div id="content">