<!-- BARRA LATERAL -->
<aside id="lateral">
    <div id="carrito" class="block_aside" >
        <h3>Carrito</h3>
        <ul>
            <?php $stats = Utils::statsCart()?>
            <li>
                <a href="<?=base_url?>cart/index">Productos (<?=$stats['count']?>)</a>   
            </li>
            <li>
                <a href="<?=base_url?>cart/index">Total ($<?=$stats['total']?>)</a>   
            </li>
            <li>
                <a href="<?=base_url?>cart/index">Ver carrito</a>   
            </li>
        </ul>
    </div>    

    <div id="login" class="block_aside" >
        <?php if( !isset($_SESSION['user']) ) :?>
            <h3>Entrar en la web</h3>
            <?php if( isset($_SESSION['error_login']) ) :?>
                <strong class="alert alert-error" ><?=$_SESSION['error_login']?></strong>
            <?php endif;?>
            <form action="<?=base_url?>user/login" method="POST">
                <label for="email">Email</label>
                <input type="email" name="email" />

                <label for="password">Password</label>
                <input type="password" name="password" />

                <input type="submit" class="button" value="Entrar">
            </form>
        <?php else: ?>
            <h3><?=$_SESSION['user']->nombre ?> <?=$_SESSION['user']->apellidos ?></h3>
        <?php endif; ?>

        <ul>
            <?php if( isset($_SESSION['admin']) ) :?>
                <li>
                    <a href="<?=base_url?>category/index">Gestionar categorías</a>
                </li>
                <li>
                    <a href="<?=base_url?>product/management">Gestionar productos</a>
                </li>
                <li>
                    <a href="<?=base_url?>order/management">Gestionar pedidos</a>
                </li>
            <?php endif; ?>
            <?php if( isset($_SESSION['user']) ) : ?>
                <li>
                    <a href="<?=base_url?>order/my_orders">Mis Pedidos</a>
                </li>
                <li>
                    <a href="<?=base_url?>user/logout">Cerrar sesión</a>
                </li>
            <?php endif; ?>
            <?php if( !isset($_SESSION['user']) && !isset($_SESSION['admin']) ):?>
                <li>
                    <a href="<?=base_url?>user/register">Registrate</a>
                </li>
            <?php endif;?>
        </ul>
    </div>
</aside>
<!-- CONTENIDO CENTRAL -->
<div id="central">
            