<?php if( isset($category) ):?>
    <h1>Categoria <?=$category->nombre ?></h1>
    
    <?php if( $products->num_rows != 0 ):?>
        <?php while($product = $products->fetch_object()) :?>
            <div class="product">
                <a href="<?=base_url?>product/view&id=<?=$product->id?>">
                    <?php if( !is_null($product->imagen) ) :?>
                        <img src="<?=base_url?>/uploads/images/<?=$product->imagen;?>" />
                    <?php else :?>
                        <img src="/assets/img/camiseta.png" />
                    <?php endif;?>
                    <h2><?=$product->nombre ?></h2>
                </a>
                <p>$<?=$product->precio ?></p>
                <a href="<?=base_url?>cart/add&id=<?=$product->id?>" class="button" >Comprar</a>
            </div>
        <?php endwhile; ?>
    <?php else :?>
        <p>No hay productos para mostrar</p>
    <?php endif; ?>
<?php else:?>
    <h1>La categoría no existe</h1>
<?php endif;?>


